// Mock data for demo mode and supervisor features.
// Types have been moved to app/lib/types.ts.

import type {
  SupervisorTask,
  SupervisorReport,
  Store,
} from "./types";

export type {
  StoreStatus,
  VisitRecord,
  SupervisorTask,
  SupervisorReport,
  TaskType,
  TaskPriority,
  TaskStatus,
} from "./types";

export const mockStores: Store[] = [
  { store_id: "store-001", name: "Farmatodo Las Mercedes",       address: "Av. Las Mercedes, Caracas",                   master_lat: 10.4920, master_lng: -66.8557, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Mónica Rubio",      contact_phone: "(212) 949-8188", contact_email: "proveedores@farmatodo.com"         },
  { store_id: "store-002", name: "Farmatodo Chacao",             address: "Calle Mohedano, El Rosal",                    master_lat: 10.4904, master_lng: -66.8541, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Dayana Villalobos", contact_phone: "(212) 949-8200", contact_email: "dayana.villalobos@farmatodo.com"   },
  { store_id: "store-003", name: "Farmatodo La Trinidad",        address: "C.C. La Trinidad, Caracas",                   master_lat: 10.4751, master_lng: -66.8367, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Andrea Meserón",    contact_phone: "(212) 944-4454", contact_email: "compras.trinidad@farmatodo.com"    },
  { store_id: "store-004", name: "Farmatodo Altamira",           address: "Av. Luis Roche, Altamira",                    master_lat: 10.4958, master_lng: -66.8499, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Omar Espinosa",     contact_phone: "(212) 944-5510", contact_email: "compras.altamira@farmatodo.com"    },
  { store_id: "store-005", name: "Farmatodo Chuao",              address: "Av. Río de Janeiro, Chuao",                   master_lat: 10.4880, master_lng: -66.8604, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Migderis Reina",    contact_phone: "(414) 161-0680", contact_email: "compras.chuao@farmatodo.com"       },
  { store_id: "store-g01", name: "Gama Los Palos Grandes",       address: "Av. Francisco de Miranda, Los Palos Grandes", master_lat: 10.4994, master_lng: -66.8439, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Yanelvis Noria",    contact_phone: "(212) 205-4322", contact_email: "jfrontado@excelsiorgama.com"       },
  { store_id: "store-g02", name: "Gama Bello Campo",             address: "Av. Luis Roche, Bello Campo",                 master_lat: 10.4965, master_lng: -66.8512, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Yesika Toro",       contact_phone: "(414) 161-0680", contact_email: "comprasfrescomarket@gmail.com"     },
  { store_id: "store-g03", name: "Gama La Castellana",           address: "Av. Principal de La Castellana",              master_lat: 10.5013, master_lng: -66.8561, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Jotfren Crespo",    contact_phone: "(212) 362-3984", contact_email: "drogueriacedis@excelsiorgama.com" },
  { store_id: "store-l01", name: "Locatel El Rosal",             address: "Calle La Guairita, El Rosal",                 master_lat: 10.4897, master_lng: -66.8530, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Laris Locatel",     contact_phone: "(212) 203-4565", contact_email: "compras2.elparaiso@locatelve.com" },
  { store_id: "store-l02", name: "Locatel Sambil",               address: "C.C. Sambil, Chacao",                         master_lat: 10.4923, master_lng: -66.8481, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Thailyn López",     contact_phone: "(212) 203-4565", contact_email: "compras1.petare@locatelve.com"    },
  { store_id: "store-s01", name: "Farmacias SAAS Macaracuay",    address: "Av. Principal de Macaracuay",                 master_lat: 10.5041, master_lng: -66.8298, active: true,  created_at: "2024-01-01T00:00:00Z", contact_name: "Angie Labrador",    contact_phone: "(424) 218-6022", contact_email: null                               },
  { store_id: "store-s02", name: "Farmacias SAAS La Candelaria", address: "Av. Este 2, La Candelaria",                   master_lat: 10.5107, master_lng: -66.9012, active: false, created_at: "2024-01-01T00:00:00Z", contact_name: null,                contact_phone: null,             contact_email: null                               },
];

export const mockSupervisor = {
  id: "mock-sup-001",
  full_name: "Ana Martínez",
  email: "supervisor@ponzivenzo.com",
  role: "supervisor" as const,
  client: "Farmatodo",
};

export const mockMerchandisers = [
  { id: "merc-001", name: "Carlos Rodríguez" },
  { id: "merc-002", name: "Luis Pérez" },
  { id: "merc-003", name: "María González" },
  { id: "merc-004", name: "Andrés Ramírez" },
];

// Helper — days ago from now
const daysAgo = (d: number, extraHours = 0) =>
  new Date(Date.now() - (d * 24 + extraHours) * 60 * 60 * 1000).toISOString();

export const mockTasks: SupervisorTask[] = [
  // ── Farmatodo ──
  {
    task_id: "task-001",
    store_id: "store-001",
    store_name: "Farmatodo Las Mercedes",
    client_name: "Farmatodo",
    merchandiser_name: "Carlos Rodríguez",
    created_at: daysAgo(0, 2),
    type: "restock",
    description: "Lineal de shampoo vacío en góndola central. Requiere reposición urgente de SKUs 1042 y 1045.",
    priority: "high",
    status: "open",
  },
  {
    task_id: "task-002",
    store_id: "store-002",
    store_name: "Farmatodo Chacao",
    client_name: "Farmatodo",
    merchandiser_name: "Luis Pérez",
    created_at: daysAgo(0, 5),
    type: "contact_manager",
    description: "Gerente de sucursal bloqueó acceso a área de bodega. Se necesita coordinación para el próximo reabastecimiento.",
    priority: "high",
    status: "open",
  },
  {
    task_id: "task-003",
    store_id: "store-004",
    store_name: "Farmatodo Altamira",
    client_name: "Farmatodo",
    merchandiser_name: "María González",
    created_at: daysAgo(1),
    type: "pricing_issue",
    description: "Etiquetas de precio del exhibidor no coinciden con el sistema POS. Diferencia de Bs. 12 en producto estrella.",
    priority: "medium",
    status: "in_progress",
  },
  {
    task_id: "task-004",
    store_id: "store-003",
    store_name: "Farmatodo La Trinidad",
    client_name: "Farmatodo",
    merchandiser_name: "Carlos Rodríguez",
    created_at: daysAgo(2),
    type: "display_damage",
    description: "Exhibidor de isla dañado en esquina inferior izquierda. Material de POP desprendido.",
    priority: "low",
    status: "resolved",
  },
  {
    task_id: "task-005",
    store_id: "store-005",
    store_name: "Farmatodo Chuao",
    client_name: "Farmatodo",
    merchandiser_name: "Luis Pérez",
    created_at: daysAgo(3),
    type: "restock",
    description: "Desabastecimiento en categoría cuidado corporal. Últimas 3 visitas registran el mismo faltante.",
    priority: "medium",
    status: "resolved",
  },
  // ── Gama ──
  {
    task_id: "task-006",
    store_id: "store-g01",
    store_name: "Gama Los Palos Grandes",
    client_name: "Gama",
    merchandiser_name: "Andrés Ramírez",
    created_at: daysAgo(1),
    type: "restock",
    description: "Faltante crítico en categoría cuidado personal. Se agotó el fin de semana.",
    priority: "high",
    status: "open",
  },
  {
    task_id: "task-007",
    store_id: "store-g02",
    store_name: "Gama Bello Campo",
    client_name: "Gama",
    merchandiser_name: "Andrés Ramírez",
    created_at: daysAgo(4),
    type: "display_damage",
    description: "Exhibidor de cabecera deteriorado por humedad. Necesita reemplazo.",
    priority: "medium",
    status: "resolved",
  },
  {
    task_id: "task-008",
    store_id: "store-g01",
    store_name: "Gama Los Palos Grandes",
    client_name: "Gama",
    merchandiser_name: "María González",
    created_at: daysAgo(6),
    type: "pricing_issue",
    description: "Precio incorrecto en gondola de shampoo. Diferencia vs precio de lista.",
    priority: "low",
    status: "resolved",
  },
  // ── Locatel ──
  {
    task_id: "task-009",
    store_id: "store-l01",
    store_name: "Locatel El Rosal",
    client_name: "Locatel",
    merchandiser_name: "Carlos Rodríguez",
    created_at: daysAgo(2),
    type: "contact_manager",
    description: "Gerente solicitó cambio en planograma. Requiere aprobación del supervisor.",
    priority: "high",
    status: "in_progress",
  },
  {
    task_id: "task-010",
    store_id: "store-l02",
    store_name: "Locatel Sambil",
    client_name: "Locatel",
    merchandiser_name: "Luis Pérez",
    created_at: daysAgo(5),
    type: "restock",
    description: "Varios SKUs sin stock. Se notificó a logística.",
    priority: "medium",
    status: "resolved",
  },
  // ── Farmacias SAAS ──
  {
    task_id: "task-011",
    store_id: "store-s01",
    store_name: "Farmacias SAAS Macaracuay",
    client_name: "Farmacias SAAS",
    merchandiser_name: "Andrés Ramírez",
    created_at: daysAgo(3),
    type: "restock",
    description: "Reposición urgente en categoría bebés. Faltante desde hace 2 semanas.",
    priority: "high",
    status: "open",
  },
  {
    task_id: "task-012",
    store_id: "store-s02",
    store_name: "Farmacias SAAS La Candelaria",
    client_name: "Farmacias SAAS",
    merchandiser_name: "María González",
    created_at: daysAgo(10),
    type: "other",
    description: "Solicitud especial de gerencia para colocar material adicional de temporada.",
    priority: "low",
    status: "resolved",
  },
];

export const mockReports: SupervisorReport[] = [
  // ── Farmatodo (días recientes) ──
  {
    visit_id: "visit-001",
    store_id: "store-001",
    store_name: "Farmatodo Las Mercedes",
    store_address: "Av. Las Mercedes, Caracas",
    client_name: "Farmatodo",
    merchandiser_name: "Carlos Rodríguez",
    check_in_time: daysAgo(0, 1),
    duration_minutes: 38,
    status: "anomaly",
    observations: "Lineal de shampoo vacío en góndola central. Se dejó nota al encargado.",
    photos_count: 4,
    location_verified: true,
    tasks_count: 1,
  },
  {
    visit_id: "visit-002",
    store_id: "store-002",
    store_name: "Farmatodo Chacao",
    store_address: "Calle Mohedano, El Rosal",
    client_name: "Farmatodo",
    merchandiser_name: "Luis Pérez",
    check_in_time: daysAgo(0, 4),
    duration_minutes: 55,
    status: "anomaly",
    observations: "Gerente bloqueó acceso a bodega. Reabastecimiento parcial completado.",
    photos_count: 6,
    location_verified: true,
    tasks_count: 1,
  },
  {
    visit_id: "visit-003",
    store_id: "store-003",
    store_name: "Farmatodo La Trinidad",
    store_address: "C.C. La Trinidad, Caracas",
    client_name: "Farmatodo",
    merchandiser_name: "María González",
    check_in_time: daysAgo(0, 6),
    duration_minutes: 42,
    status: "completed",
    observations: "Visita sin novedades. Planograma correcto, exhibidor limpio y surtido.",
    photos_count: 3,
    location_verified: true,
    tasks_count: 0,
  },
  {
    visit_id: "visit-004",
    store_id: "store-004",
    store_name: "Farmatodo Altamira",
    store_address: "Av. Luis Roche, Altamira",
    client_name: "Farmatodo",
    merchandiser_name: "María González",
    check_in_time: daysAgo(1, 2),
    duration_minutes: 30,
    status: "completed",
    observations: "Reabastecimiento completo. Se corrigió precios en etiquetas.",
    photos_count: 5,
    location_verified: true,
    tasks_count: 1,
  },
  {
    visit_id: "visit-005",
    store_id: "store-005",
    store_name: "Farmatodo Chuao",
    store_address: "Av. Río de Janeiro, Chuao",
    client_name: "Farmatodo",
    merchandiser_name: "Carlos Rodríguez",
    check_in_time: daysAgo(1, 3),
    duration_minutes: 0,
    status: "skipped",
    observations: "Sucursal cerrada por inventario interno.",
    photos_count: 1,
    location_verified: false,
    tasks_count: 0,
  },
  {
    visit_id: "visit-006",
    store_id: "store-001",
    store_name: "Farmatodo Las Mercedes",
    store_address: "Av. Las Mercedes, Caracas",
    client_name: "Farmatodo",
    merchandiser_name: "Luis Pérez",
    check_in_time: daysAgo(2, 2),
    duration_minutes: 45,
    status: "completed",
    observations: "Visita de rutina completada. Planograma actualizado.",
    photos_count: 4,
    location_verified: true,
    tasks_count: 0,
  },
  {
    visit_id: "visit-007",
    store_id: "store-002",
    store_name: "Farmatodo Chacao",
    store_address: "Calle Mohedano, El Rosal",
    client_name: "Farmatodo",
    merchandiser_name: "Andrés Ramírez",
    check_in_time: daysAgo(3),
    duration_minutes: 35,
    status: "anomaly",
    observations: "Precio incorrecto detectado en 4 SKUs. Se reportó a administración.",
    photos_count: 3,
    location_verified: true,
    tasks_count: 1,
  },
  // ── Gama ──
  {
    visit_id: "visit-008",
    store_id: "store-g01",
    store_name: "Gama Los Palos Grandes",
    store_address: "Av. Francisco de Miranda, Los Palos Grandes",
    client_name: "Gama",
    merchandiser_name: "Andrés Ramírez",
    check_in_time: daysAgo(0, 2),
    duration_minutes: 50,
    status: "anomaly",
    observations: "Faltante en categoría cuidado personal. Se generó tarea de restock.",
    photos_count: 5,
    location_verified: true,
    tasks_count: 1,
  },
  {
    visit_id: "visit-009",
    store_id: "store-g02",
    store_name: "Gama Bello Campo",
    store_address: "Av. Luis Roche, Bello Campo",
    client_name: "Gama",
    merchandiser_name: "Andrés Ramírez",
    check_in_time: daysAgo(2),
    duration_minutes: 40,
    status: "completed",
    observations: "Visita sin novedades. Planograma completo y correcto.",
    photos_count: 2,
    location_verified: true,
    tasks_count: 0,
  },
  {
    visit_id: "visit-010",
    store_id: "store-g01",
    store_name: "Gama Los Palos Grandes",
    store_address: "Av. Francisco de Miranda, Los Palos Grandes",
    client_name: "Gama",
    merchandiser_name: "María González",
    check_in_time: daysAgo(5),
    duration_minutes: 45,
    status: "anomaly",
    observations: "Exhibidor de cabecera dañado. Se solicitó reemplazo.",
    photos_count: 4,
    location_verified: true,
    tasks_count: 1,
  },
  {
    visit_id: "visit-011",
    store_id: "store-g03",
    store_name: "Gama La Castellana",
    store_address: "Av. Principal de La Castellana",
    client_name: "Gama",
    merchandiser_name: "Luis Pérez",
    check_in_time: daysAgo(6),
    duration_minutes: 30,
    status: "completed",
    observations: "Reposición completa realizada sin inconvenientes.",
    photos_count: 2,
    location_verified: true,
    tasks_count: 0,
  },
  // ── Locatel ──
  {
    visit_id: "visit-012",
    store_id: "store-l01",
    store_name: "Locatel El Rosal",
    store_address: "Calle La Guairita, El Rosal",
    client_name: "Locatel",
    merchandiser_name: "Carlos Rodríguez",
    check_in_time: daysAgo(1),
    duration_minutes: 60,
    status: "anomaly",
    observations: "Gerente solicitó cambio en planograma. Pendiente aprobación.",
    photos_count: 3,
    location_verified: true,
    tasks_count: 1,
  },
  {
    visit_id: "visit-013",
    store_id: "store-l02",
    store_name: "Locatel Sambil",
    store_address: "C.C. Sambil, Chacao",
    client_name: "Locatel",
    merchandiser_name: "Luis Pérez",
    check_in_time: daysAgo(4),
    duration_minutes: 50,
    status: "completed",
    observations: "Reposición completa. SKUs faltantes repuestos.",
    photos_count: 4,
    location_verified: true,
    tasks_count: 0,
  },
  {
    visit_id: "visit-014",
    store_id: "store-l01",
    store_name: "Locatel El Rosal",
    store_address: "Calle La Guairita, El Rosal",
    client_name: "Locatel",
    merchandiser_name: "Carlos Rodríguez",
    check_in_time: daysAgo(8),
    duration_minutes: 45,
    status: "completed",
    observations: "Visita de seguimiento. Planograma correcto.",
    photos_count: 2,
    location_verified: true,
    tasks_count: 0,
  },
  // ── Farmacias SAAS ──
  {
    visit_id: "visit-015",
    store_id: "store-s01",
    store_name: "Farmacias SAAS Macaracuay",
    store_address: "Av. Principal de Macaracuay",
    client_name: "Farmacias SAAS",
    merchandiser_name: "Andrés Ramírez",
    check_in_time: daysAgo(2),
    duration_minutes: 55,
    status: "anomaly",
    observations: "Faltante crítico en categoría bebés. Se escaló a logística.",
    photos_count: 5,
    location_verified: true,
    tasks_count: 1,
  },
  {
    visit_id: "visit-016",
    store_id: "store-s02",
    store_name: "Farmacias SAAS La Candelaria",
    store_address: "Av. Este 2, La Candelaria",
    client_name: "Farmacias SAAS",
    merchandiser_name: "María González",
    check_in_time: daysAgo(9),
    duration_minutes: 40,
    status: "completed",
    observations: "Material de temporada colocado según instrucciones.",
    photos_count: 3,
    location_verified: true,
    tasks_count: 0,
  },
  {
    visit_id: "visit-017",
    store_id: "store-s01",
    store_name: "Farmacias SAAS Macaracuay",
    store_address: "Av. Principal de Macaracuay",
    client_name: "Farmacias SAAS",
    merchandiser_name: "Andrés Ramírez",
    check_in_time: daysAgo(15),
    duration_minutes: 35,
    status: "anomaly",
    observations: "Segundo reporte de faltante en bebés. Problema de inventario persistente.",
    photos_count: 2,
    location_verified: true,
    tasks_count: 1,
  },
];
